// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20210122175837_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.NationalPark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acres");

                    b.Property<string>("DateEstablished");

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("YearlyVisitors");

                    b.HasKey("Id");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acres = "3,223,383.43 acres",
                            DateEstablished = "December 2, 1980",
                            Description = "Glacier Bay contains tidewater glaciers, mountains, fjords, and a temperate rainforest, and is home to large populations of grizzly bears, mountain goats, whales, seals, and eagles. When discovered in 1794 by George Vancouver, the entire bay was covered by ice, but the glaciers have since receded more than 65 miles",
                            Location = "Alaska",
                            Name = "Glacier Bay",
                            YearlyVisitors = "672087"
                        },
                        new
                        {
                            Id = 2,
                            Acres = "221,390.21",
                            DateEstablished = "December 9, 1962",
                            Description = "This portion of the Chinle Formation has a large concentration of 225-million-year-old petrified wood. The surrounding Painted Desert features eroded cliffs of red-hued volcanic rock called bentonite. Dinosaur fossils and over 350 Native American sites are also protected in this park.",
                            Location = "Arizona",
                            Name = "Petrified Forest",
                            YearlyVisitors = "643,588 acres"
                        },
                        new
                        {
                            Id = 3,
                            Acres = "138,999.37 acres",
                            DateEstablished = "June 29, 1906",
                            Description = "This area constitutes over 4,000 archaeological sites of the Ancestral Puebloan people, who lived here and elsewhere in the Four Corners region for at least 700 years. Cliff dwellings built in the 12th and 13th centuries include Cliff Palace, which has 150 rooms and 23 kivas, and the Balcony House, with its many passages and tunnels.",
                            Location = "Colorado",
                            Name = "Mesa Verde",
                            YearlyVisitors = "556,203"
                        },
                        new
                        {
                            Id = 4,
                            Acres = "172,971.11 acres",
                            DateEstablished = "June 28, 1980",
                            Description = "Located in Biscayne Bay, this park at the north end of the Florida Keys has four interrelated marine ecosystems: mangrove forest, the Bay, the Keys, and coral reefs. Threatened animals include the West Indian manatee, American crocodile, various sea turtles, and peregrine falcon.",
                            Location = "Florida",
                            Name = "Biscayne",
                            YearlyVisitors = "708,522"
                        },
                        new
                        {
                            Id = 5,
                            Acres = "49,076.63 acres",
                            DateEstablished = "February 26, 1919",
                            Description = "Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes. There are freshwater, estuary, forest, and intertidal habitats.",
                            Location = "Maine",
                            Name = "Acadia",
                            YearlyVisitors = "3,437,286"
                        },
                        new
                        {
                            Id = 6,
                            Acres = "218,222.35 acres",
                            DateEstablished = "April 8, 1975",
                            Description = "This park protecting four lakes near the Canada–US border is a site for canoeing, kayaking, and fishing. The park also preserves a history populated by Ojibwe Native Americans, French fur traders called voyageurs, and gold miners. Formed by glaciers, the region features tall bluffs, rock gardens, islands, bays, and several historic buildings.",
                            Location = "Minnesota",
                            Name = "Voyageurs",
                            YearlyVisitors = "232,974"
                        });
                });

            modelBuilder.Entity("Parks.Models.StatePark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Camping");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Region");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Camping = "No",
                            Description = "Fort Rock Cave was the site of the earliest evidence of human habitation in the US state of Oregon before the excavation of Paisley Caves. Fort Rock Cave featured numerous well-preserved sagebrush sandals, ranging from 9,000 to 13,000 years old. The cave is located approximately 1.5 miles (2.4 km) west of Fort Rock near Fort Rock State Natural Area in Lake County. Fort Rock Cave was declared a National Historic Landmark in 1961, and added to the National Register of Historic Places in 1966.",
                            Name = "Fort Rock Cave",
                            Region = "Central Oregon",
                            State = "Oregon"
                        },
                        new
                        {
                            Id = 2,
                            Camping = "Yes",
                            Description = "Smith Rock State Park is a state park located in central Oregon's High Desert near the communities of Redmond and Terrebonne. The day-use area of the park is open daily from dawn to dusk. The park also has a camping area as well that accommodates tent camping only. Its sheer cliffs of tuff and basalt are ideal for rock climbing of all difficulty levels. Smith Rock is generally considered the birthplace of modern American sport climbing, and is host to cutting-edge climbing routes. It is popular for sport climbing, traditional climbing, multi-pitch climbing, and bouldering.",
                            Name = "Smith Rock State Park",
                            Region = "Central Oregon",
                            State = "Oregon"
                        },
                        new
                        {
                            Id = 3,
                            Camping = "Yes",
                            Description = "Golden is an abandoned mining town located at Coyote Creek in Josephine County, Oregon, United States.",
                            Name = "Golden State Heritage Site",
                            Region = "Southern Oregon",
                            State = "Oregon"
                        },
                        new
                        {
                            Id = 4,
                            Camping = "Yes",
                            Description = "Sunset Bay State Park is a state park in the U.S. state of Oregon. Administered by the Oregon Parks and Recreation Department, it is about 0.4 miles (0.6 km) south of Cape Arago Lighthouse and 2.5 miles (4.0 km) outside the town of Charleston on Coos Bay. The park offers a crescent shaped beach, tide pools, hiking trails and a year-round campground.",
                            Name = "Sunset Bay State Park",
                            Region = "South Coast",
                            State = "Oregon"
                        },
                        new
                        {
                            Id = 5,
                            Camping = "No",
                            Description = "Sheridan State Scenic Corridor is a state park in the Columbia River Gorge, west of Cascade Locks, Oregon. The 11-acre (4.5 ha) property, containing an old-growth forest, is located on the south side of Interstate 84 at approximately milepoint 42.5, and was not accessible by motor vehicle since I-84 was built in 1960. However, with the opening of the Eagle Creek-Cascade Locks segment of the Historic Columbia River Highway State Trail in 1998, it has become easily accessible by foot or bicycle. The park is on a triangular lot, completely surrounded by I-84 and the Mount Hood National Forest.",
                            Name = "Sheridan State Scenic Corridor",
                            Region = "Portland/Columbia Gorge",
                            State = "Oregon"
                        },
                        new
                        {
                            Id = 6,
                            Camping = "No",
                            Description = "Oswald West State Park is part of the state park system of the U.S. state of Oregon. It is located about 10 miles (16 km) south of the city of Cannon Beach, adjacent to Arch Cape, on the Pacific Ocean. The park covers 2,448 acres (9.91 km2), with many miles of hiking trails both inside the park grounds and linking to other parks and landmarks beyond.",
                            Name = "Oswald West State Park",
                            Region = "North Coast",
                            State = "Oregon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
